### ISSUE TITLE
入力された値を取得できるように仕様変更

### ISSUE THREAD

**Issue by KEiJey** [hacku-chamomilla/gamename-front-end#26]
## ✨ 概要

- 入力された値を取得できるように仕様変更 #21

## 🔥 ゴール

- 前回は入力された値はそのままだったのでこれを格納するように変更

## ✅ タスク

- [ ] 入力された値を取得できるようにする

**Comment by ltoppyl** [comment]
Issue は雑に使ってもらって良いから、参考にしたサイトとか Issue のコメントに残しとくと良いかも！？
